blueprint:
  name: Light Sync
  description: "Sync the on/off state and brightness of one light to another light(s)\n\nThe following recommended settings will help make the transitions more fluid:\n\n- 
    Transitions from on/off/etc should be set to 0 for all devices\n- Default On Level should match for all devices \n- The device settings for the Controlling Light 
    should not have a minimum brigtness"
  domain: automation
  input:
    controlling_light:
      name: Controlling Light
      description: Input the light entity that will be in control
      selector:
        entity:
          filter:
          - domain:
            - light
          multiple: false
    target_light:
      name: Target Light
      description: Input the light entity/entities that will sync to the Controlling Light
      selector:
        entity:
          filter:
          - domain:
            - light
          multiple: true
    min_brightness:
      name: Min Brightness
      description: Set the minimum brightness for the target light(s), as a percentage (1-100).
      default: 1
      selector:
        number:
          min: 1
          max: 100
mode: restart
max_exceeded: silent
variables:
  controllingLight: !input controlling_light
  controllingLightBrightness: |
    {{ (state_attr(controllingLight, 'brightness') / 2.55) }}
  minBrightness: !input min_brightness
  brightnessValue: |
    {{ ((((100 - minBrightness) / 99 ) * controllingLightBrightness + minBrightness - (100 - minBrightness) / 99 ) * 2.55) | round(0) }}
trigger:
- platform: state
  entity_id: !input controlling_light
- platform: state
  entity_id: !input controlling_light
  attribute: brightness
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input controlling_light
            state: "on"
        sequence:
          - data:
              brightness: '{{ brightnessValue }}'
            action: light.turn_on
            target:
              entity_id: !input target_light
      - conditions:
          - condition: state
            entity_id: !input controlling_light
            state: "off"
        sequence:
          - data:
              entity_id: !input target_light
            action: light.turn_off